### ISSUE TITLE
what is this?

### ISSUE THREAD

**Issue by annihat** [termux/termux-failsafe#1]
Hi, 
is this what I see when I long-press the home-screen icon? 

What does it mean?
Where can I find a full description of it?

**Comment by Grimler91** [comment]
On older android versions it is not possible to have the type of menu that appears when you long-press the icon. This app was a suggested alternative way to get a [failsafe session](https://wiki.termux.com/wiki/Recover_a_broken_environment), it just adds a second icon to your home screen that opens termux in failsafe-mode. 

We never released this app though, devices without the possibility to long-press the home screen icon have to long-press the menu button in the app to get a failsafe session.

For further details see the code.
